import Foundation

/// Bridge to the Rust `garden-ffi` dynamic library.
///
/// This class wraps the C-ABI functions exported by the Rust `cdylib`
/// (`libgarden_ffi.dylib`). The header `garden_ffi.h` is generated by
/// `cbindgen` from the Rust source.
///
/// Usage:
///   1. Build the Rust crate: `cargo build -p garden-ffi`
///   2. Link `libgarden_ffi.dylib` into the Xcode project
///   3. Add the bridging header that imports `garden_ffi.h`
class RustBridge {
    private var engine: OpaquePointer?

    init() {
        // TODO: Call garden_engine_create() once the dylib is linked
        // engine = garden_engine_create()
    }

    deinit {
        // TODO: Call garden_engine_destroy(engine) once the dylib is linked
        // if let engine = engine {
        //     garden_engine_destroy(engine)
        // }
    }

    /// Start the MCP server on the given port.
    func startMCPServer(port: UInt16) -> Bool {
        // TODO: Call garden_mcp_start(engine, port) once linked
        // guard let engine = engine else { return false }
        // let status = garden_mcp_start(engine, port)
        // return status == GARDEN_STATUS_OK
        print("🌿 [RustBridge] MCP server start requested on port \(port)")
        return true
    }

    /// Send a JSON request to the Rust engine and receive a JSON response.
    func sendRequest(json: String) -> String? {
        // TODO: Call garden_send_request(engine, json) once linked
        // guard let engine = engine else { return nil }
        // let cStr = json.withCString { ptr in
        //     garden_send_request(engine, ptr)
        // }
        // guard let cStr = cStr else { return nil }
        // let result = String(cString: cStr)
        // garden_free_string(cStr)
        // return result
        print("🌿 [RustBridge] Request: \(json)")
        return "{\"type\":\"error\",\"message\":\"not yet linked\"}"
    }
}
